language: java
jdk:
  - oraclejdk8
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - postgresql
  - mysql
before_install:
    - export TZ=Europe/London
before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database test;'
  - sudo docker run --name=sqlserver -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=YourStrong!Passw0rd' -p 1433:1433 -d microsoft/mssql-server-linux:2017-latest
  - sudo docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'create database test'
script:
  - mvn clean package -DskipTests=true
  - mvn test -Dtest=UnitTestSuite
  - mvn test -Dtest=MySqlTestSuite
  - mvn test -Dtest=PostgreSqlTestSuite
  - mvn test -Dtest=SqlServerTestSuite
cache:
  directories:
  - $HOME/.m2
